# Site settings
title: "小信号"
subtitle: "SEES-QUOTATION"
description: "一些金句一些思考 一些优质信息源"
author: "大黑天"
email: ""

# GitHub 配置
github_username: daheitian
github_repo: seesquotes

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Data files
data_dir: _data

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - scripts/
  - README.md
  - .github/

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
